name: CI Tests

on:
  - pull_request
  - push

env:
  CI: true

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 20.x
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - name: Copy mock config
        run: mkdir functions/config && cp functions/src/test/mock_data/config.json functions/config/config.json

      - name: Run tests
        run: make test-functions
